"""added subprogram.

Revision ID: 3edb391a5354
Revises: 2effef51aaa9
Create Date: 2025-11-06 21:46:52.563446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edb391a5354'
down_revision = '2effef51aaa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_file', sa.String(length=255), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_file'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))

    op.drop_table('sub_program')
    # ### end Alembic commands ###
