"""added socials column.

Revision ID: fae9858b0101
Revises: d855a540538e
Create Date: 2025-11-11 19:24:40.062760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae9858b0101'
down_revision = 'd855a540538e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('our_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('thread_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('our_team', schema=None) as batch_op:
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('thread_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
